services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgvector
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
      - UTC=-3
      - TIMEZONE=America/Sao_Paulo
    ports:
      - "5455:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - pgvector_net
    command: postgres   
     
volumes:
  pgvector_data:
    driver: local

networks:
  pgvector_net:
    name: pgvector_net
    driver: bridge
    attachable: true
